### PR TITLE
Hotfix/existing dir

### PR DESCRIPTION
**Pull request by Mech7**
When the tmp path is empty but the components are already installed i get an error like below.
Checking for the install path seems to work.

```
WARNING: JFolder: :files: Path is not a folder. Path: tmp/picturae/com_archive [jerror]
WARNING: JFolder: :files: Path is not a folder. Path: tmp/picturae/com_archive [jerror]



  [ErrorException]
  array_merge(): Argument #1 is not an array



Exception trace:
 () at /Users/cdekok/Projects/hni.jos.picturae.pro/public/libraries/cms/installer/installer.php:1875
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 array_merge() at /Users/cdekok/Projects/hni.jos.picturae.pro/public/libraries/cms/installer/installer.php:1875
 JInstaller->findManifest() at /Users/cdekok/Projects/hni.jos.picturae.pro/public/libraries/cms/installer/installer.php:276
 JInstaller->getManifest() at /Users/cdekok/Projects/hni.jos.picturae.pro/cust-hni-website/external-src/src/vendor/joomlatools/installer/src/Joomlatools/Composer/ExtensionInstaller.php:151
 Joomlatools\Composer\ExtensionInstaller->isInstalled() at phar:///Users/cdekok/bin/composer/src/Composer/Installer/InstallationManager.php:127
 Composer\Installer\InstallationManager->isPackageInstalled() at phar:///Users/cdekok/bin/composer/src/Composer/Factory.php:469
 Composer\Factory->purgePackages() at phar:///Users/cdekok/bin/composer/src/Composer/Factory.php:300
 Composer\Factory->createComposer() at phar:///Users/cdekok/bin/composer/src/Composer/Factory.php:486
 Composer\Factory::create() at phar:///Users/cdekok/bin/composer/src/Composer/Console/Application.php:222
 Composer\Console\Application->getComposer() at phar:///Users/cdekok/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///Users/cdekok/bin/composer/src/Composer/Command/UpdateCommand.php:86
 Composer\Command\UpdateCommand->execute() at phar:///Users/cdekok/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///Users/cdekok/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/cdekok/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///Users/cdekok/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///Users/cdekok/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///Users/cdekok/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///Users/cdekok/bin/composer/bin/composer:43
 require() at /Users/cdekok/bin/composer:25
```

### CODE REVIEW

**Comment by stevenrombauts** [comment]
Thank you @Mech7, this does seem to get rid of the error.

The actual issue here is the fact that we are still using the `tmp` folder to unpack extensions before installing them. Since a tmp folder can be emptied anytime it's not a reliable way to check if a component is still installed.

I'll need to test it a bit more but the proper solution will be to just let the downloaded files sit in `vendor` instead of `tmp` and load the manifest from there.

**Comment by Mech7** [comment]
Is there a reason that the components must be there? Normally in our build process we just start a build from scratch so it would not have a vendor dir yet.

**Comment by stevenrombauts** [comment]
The problem here is that Composer calls the isInstalled() method before anything else. 

Firstly, we do need a location where Composer will extract/clone the files before we install them into Joomla.

Secondly, we need to check if an extension is installed or not so we can either call `update` or `install`. To do so, we need to get the type and element name from the manifest. ([code](https://github.com/Mech7/joomla-composer/blob/1e5ba773628f45a2d8f94d8b29f67ed019524377/src/Joomlatools/Composer/ExtensionInstaller.php#L160-L163)). The files aren't downloaded when the `isInstalled()` method is invoked so we know nothing about the extension we will be installing. That means we also have no clue what type of extension it is and where the manifest might be.

If the files remain in vendor we can use that location to read the manifest, then check in Joomla's database if the extension is already installed or not.

Now, if you are rebuilding from scratch each time, this is not an issue at all since you will install your extensions for the first time (so `isInstalled()` can perfectly return false). You don't need to have the vendor directory, composer will create it. 

Does that make sense?

**Comment by Mech7** [comment]
Ah yes makes sense 😊this will be better then

**Comment by stevenrombauts** [comment]
I've tested this some more with a couple of different extensions and happy to report everything is working as it should.

Thanks again for your help @Mech7

**Pull request merged**
